# Generated by Django 5.2.11 on 2026-02-11 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=100)),
                ('criticality', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50)),
                ('lifecycle', models.CharField(max_length=50)),
                ('business_owner', models.CharField(max_length=255)),
                ('it_owner', models.CharField(max_length=255)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('programming_languages', models.CharField(max_length=255)),
                ('database', models.CharField(max_length=255)),
                ('hosting_environment', models.CharField(max_length=255)),
                ('capabilities', models.TextField()),
                ('technical_dependencies', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=50)),
                ('data_volume', models.CharField(max_length=100)),
                ('data_sensitivity', models.CharField(max_length=100)),
                ('source_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_integrations', to='portfolio.application')),
                ('target_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_integrations', to='portfolio.application')),
            ],
        ),
    ]
